// <auto-generated />
using Gimpies_Blazor1.Database.Models.Entities;
using Microsoft.AspNetCore.Components;
using MudBlazor;

namespace Gimpies_Blazor1.Components.Pages.Dialogs
{
    public partial class BuyShoesDialog
    {
        [Parameter] public Shoe Shoe { get; set; }
        [CascadingParameter] MudDialogInstance MudDialogInstance { get; set; } // Gebruik MudDialogInstance


        private int Quantity;

        private void Submit()
        {
            if (Quantity > 0)
            {
                MudDialogInstance.Close(DialogResult.Ok(Quantity));
            }
        }

        private void Cancel()
        {
            MudDialogInstance.Cancel();
        }
    }
}