// <auto-generated />
using Gimpies_Blazor1.Database.Models.Entities;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.EntityFrameworkCore;
using MudBlazor;

namespace Gimpies_Blazor1.Components.Pages.Dialogs
{
    public partial class ConfirmDialog
    {
        [Parameter] public Shoe Shoe { get; set; }
        [Parameter] public string ButtonText { get; set; }
        [Parameter] public string ActionType { get; set; }
        [Parameter] public int Quantity { get; set; }
        [Parameter] public Shoe newShoe { get; set; }
        [Parameter] public int shoeToDelete { get; set; }
        [Parameter] public User newUser { get; set; }
        [Parameter] public int userToDelete { get; set; }
        private string uploadedImageUrl { get; set; }



        [CascadingParameter] MudDialogInstance MudDialogInstance { get; set; } // Gebruik MudDialogInstance

        private List<Role> roles;

        protected override async Task OnInitializedAsync()
        {
            roles = await DbContext.Roles.ToListAsync();
        }

        private async Task HandleFileSelected(InputFileChangeEventArgs e)
        {
            // Upload bestand en sla de URL op
            var uploadedFile = e.File;
            if (uploadedFile != null)
            {
                // Simuleer een URL na uploaden (je kunt dit vervangen door je eigen uploadlogica)
                uploadedImageUrl = $"https://example.com/uploads/{uploadedFile.Name}";

                // Koppel de geüploade URL aan de nieuwe schoen
                if (newShoe != null)
                {
                    newShoe.ImageUrl = uploadedImageUrl;
                }
            }
        }

        private void Submit()
        {

            if (Quantity > 0)
            {
                MudDialogInstance.Close(DialogResult.Ok(Quantity));
            }

            else if (newShoe != null)
            {
                // Zorg ervoor dat de geüploade afbeelding wordt opgenomen
                if (!string.IsNullOrEmpty(uploadedImageUrl))
                {
                    newShoe.ImageUrl = uploadedImageUrl;
                }

                MudDialogInstance.Close(DialogResult.Ok(newShoe));
            }

            else if (shoeToDelete != null)
            {
                MudDialogInstance.Close(DialogResult.Ok(shoeToDelete));

            }
            else if (Shoe != null)
            {
                MudDialogInstance.Close(DialogResult.Ok(Shoe));
            }
            else if (newUser != null)
            {
                MudDialogInstance.Close(DialogResult.Ok(newUser));
            }
            else if (userToDelete != null)
            {
                MudDialogInstance.Close(DialogResult.Ok(userToDelete));
            }
            else
            {
                MudDialogInstance.Cancel();
            }

        }

        private void Cancel()
        {
            MudDialogInstance.Cancel();
        }
    }
}