// <auto-generated />
using Gimpies_Blazor1.Database.Models.Entities;
using Microsoft.EntityFrameworkCore;
using MudBlazor;
namespace Gimpies_Blazor1.Components.Pages.Admin
{
    public partial class SalesOverview
    {

        private string mostSoldShoe;
        private string leastSoldShoe;
        private decimal totalSales;

        protected override async Task OnInitializedAsync()
        {
            var salesData = await DbContext.SalesTransactions
                .Include(st => st.Shoe)
                .ThenInclude(s => s.Brand)
                .Include(st => st.Shoe)
                .ThenInclude(s => s.Model)
                .GroupBy(st => st.ShoeId)
                .Select(group => new
                {
                    ShoeId = group.Key,
                    TotalSold = group.Sum(st => st.Quantity),
                    TotalRevenue = group.Sum(st => st.Quantity * st.Price),
                    Shoe = group.FirstOrDefault().Shoe
                })
                .ToListAsync();


            var mostSold = salesData.OrderByDescending(sd => sd.TotalSold).FirstOrDefault();
            mostSoldShoe = mostSold != null
                ? $"{mostSold.Shoe.Brand.BrandName} {mostSold.Shoe.Model.ModelName} ({mostSold.TotalSold} paar)"
                : "Geen schoenen verkocht.";

            var leastSold = salesData.OrderBy(sd => sd.TotalSold).FirstOrDefault();
            leastSoldShoe = leastSold != null
                ? $"{leastSold.Shoe.Brand.BrandName} {leastSold.Shoe.Model.ModelName} ({leastSold.TotalSold} paar)"
                : "Geen schoenen verkocht.";

            totalSales = salesData.Sum(sd => sd.TotalRevenue);
        }


    }
}