// <auto-generated />
using Microsoft.AspNetCore.Components;
using MudBlazor;

namespace Gimpies_Blazor1.Components.Pages
{
    public partial class ConfirmDialog
    {
        [CascadingParameter] MudDialogInstance MudDialog { get; set; }
        [Parameter] public string ContentText { get; set; }
        [Parameter] public string ButtonText { get; set; }
        [Parameter] public Color Color { get; set; }

        private void Confirm() => MudDialog.Close(DialogResult.Ok(true));
        private void Cancel() => MudDialog.Close(DialogResult.Cancel);


    }
}